theme: jekyll-theme-slate
title: Alorithmen und Datenstrukturen II - Implementation of Perlin Noise - Team dingo
description: Implemented by Chris Brammer, Sven Schatter, Oliver Hauser and Michael Eggers
